[project]
authors = [
  "Anna Störiko <a.storiko@tudelft.nl>",
  "Adrian Seyboldt <adrian.seyboldt@gmail.com>",
]
channels = ["conda-forge"]
name = "reactix"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
ipykernel = ">=6.29.5"
numpy = ">=2.2.4"
seaborn = ">=0.13.2"
matplotlib = ">=3.10.1"
arviz = ">=0.21.0"
maturin = ">=1.8.3"
zarr = ">=3.0.6,<4"
jupyterlab = ">=4.4.1"
pytest = ">=8.4.1"
ipympl = ">=0.9.7"
pip = ">=25.2"
nutpie = "<0.16.0"
pymc = ">=5.26.0"


[pypi-dependencies]
reactix = { path = ".", editable = true }
flowjax = ">=17.1.1"
tensorflow-probability = ">=0.25.0"
diffrax = "*"
jax = { version = "*", extras = [] }
