[project]
authors = [
  "Anna Störiko <a.storiko@tudelft.nl>",
  "Adrian Seyboldt <adrian.seyboldt@gmail.com>",
]
channels = ["conda-forge"]
name = "kinetix"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
develop = { cmd = "maturin develop --release --uv", cwd = "../nuts-py" }

[dependencies]
ipykernel = ">=6.29.5,<7"
numpy = ">=2.2.4,<3"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.10.1,<4"
arviz = ">=0.21.0,<0.22"
maturin = ">=1.8.3,<2"
zarr = ">=3.0.6,<4"
jupyterlab = ">=4.4.1,<5"
pytest = ">=8.4.1,<9"
ipympl = ">=0.9.7,<0.10"

[pypi-dependencies]
kinetix = { path = ".", editable = true }
pytensor = { git = "https://github.com/aseyboldt/pytensor.git", rev = "4d7c6ed66cbae747af5243dbd3f33b4a3ed7bac9" }
pymc = ">=2.22.0"
cloudpickle = ">=3.1.1, <4"
cachetools = ">=5.5.2, <6"
rich = ">=13.9.4, <14"
threadpoolctl = ">=3.6.0, <4"
flowjax = ">=17.1.1, <18"
tensorflow-probability = ">=0.25.0, <0.26"
diffrax = "*"
jax = { version = "*", extras = ["cuda12"] }
